Bug/solo mostrar available
BealeStBluesBoy/bookli pull request #19
Opened 2020-07-01 02:39 UTC by SoraireEmmanuel

Che gustavo ahi te lo dejo no mergea automaticamente, creo que se pisa con el test de leo.

2020-07-01 19:07 UTC, leosfigueira commented on client/js/home.js
>      status: '',
Queda el status definido dos veces?

2020-07-01 19:45 UTC, SoraireEmmanuel commented on client/js/home.js
>      status: '',
no leo, la modificación es que en status se inicializa en AVAILABLE, el que esta vacio no iria, no me di cuenta al hacer el comit

2020-07-01 19:54 UTC, SoraireEmmanuel commented on client/js/home.js
>      status: '',
ya arregle el error, ahora tendría que estar bien

2020-07-02 23:45 UTC, gusalecar requested changes

2020-07-02 23:45 UTC, BealeStBluesBoy commented on test/e2e/index.test.js
> +    test.only('Deberia mostrar solo los libros en estado AVAILABLE al iniciar home', browser => {
Te olvidaste de sacar el only

2020-07-03 00:16 UTC, SoraireEmmanuel commented on test/e2e/index.test.js
> +    test.only('Deberia mostrar solo los libros en estado AVAILABLE al iniciar home', browser => {
Listo ya le saque el only y ejecute de nuevo todos los test. Corre todo ahi pushie asi que mergea tranqui

2020-07-03 00:43 UTC, gusalecar approved these changes

2020-07-03 00:49 UTC, merged